### get all
GET http://localhost:8080/landmarks/getAll

### get by ID
GET http://localhost:8080/landmarks/getById/1

### trying search wrong ID
GET http://localhost:8080/landmarks/getById/999

### New json without image
POST http://localhost:8080/landmarks/save
Content-Type: application/json

{
  "id": 0,
  "name": "Башня",
  "city": "Москва",
  "landmarkAddress": "ул. Петрозаводская, 18",
  "undergrounds": "Красная площадь",
  "landmarkDescription": "Самая высокая башня мира",
  "landmarkWebSite": "default",
  "workingTime": "default",
  "landmarkPhone": "default"
}

### removeById
POST http://localhost:8080/landmarks/removeById/1

### restoreById
POST http://localhost:8080/landmarks/restoreById/1